### ISSUE TITLE
Markierte Kurse

### ISSUE THREAD

**Issue by Paramian** [lavaloop-official/GovLearn-client#23]
Ich würde die Kurse in der Übersicht aller markierten Kurse gerne Clickable machen und nicht nur den Titel :). Was meint ihr dazu?

**Comment by Mrjulss** [comment]
Fänd ich cool, das ist auf der main seite glaube ich auch noch nicht, außer das wurd jetzt geändert. Hätte auch eigentlich intuitiv gedacht man kann da auch aufs bild clicken.
