### ISSUE TITLE
Weird format on detail page when image is to small

### ISSUE THREAD

**Issue by Paramian** [lavaloop-official/GovLearn-client#54]

**Comment by Paramian** [comment]
![Uploading Detailpage.png…]()

**Comment by Paramian** [comment]
![Detailpage](https://github.com/lavaloop-official/GovLearn-client/assets/84677055/f620516b-f057-4bcd-a240-6173033516d2)

**Comment by Mrjulss** [comment]
kriege den noch nicht rekonstruiert
