### ISSUE TITLE
false navigation on profile click

### ISSUE THREAD

**Issue by Mrjulss** [lavaloop-official/GovLearn-client#55]
![image](https://github.com/lavaloop-official/GovLearn-client/assets/95315819/8ffe8166-4fc0-4e37-bab1-7c6f2acd9e04)
Finde die Schaltfläche eigentlich auch intuitiv für die Profil-Ansicht da gelangt man jedoch zu http://localhost:5173/detail/profile und nicht zu http://localhost:5173/profile

**Comment by comlit** [comment]
hab ich gerade auch gesehen. PR ist offen
