### ISSUE TITLE
Gruppen - Kurszuweisung

### ISSUE THREAD

**Issue by comlit** [lavaloop-official/GovLearn-client#72]
kurszuweisung ist buggy, manchmal wird doppelt zugeordnet. ich blick durch den code nicht durch also ka woran das liegt
![image](https://github.com/lavaloop-official/GovLearn-client/assets/67443177/67ce7b8b-5be1-46dc-888c-dfe6e7502d5e)

**Comment by Mrjulss** [comment]
Habs jetzt mal probiert, dass der Endpunkt den Kurs wiedergibt, dann lässt sich aber auch irgendwie nur ein Kurs hinzufügen und weitere werden nicht angezeigt. Probier nochmal dass man im Endpunkt einfach mehrere Kurs Ids übergibt
