### ISSUE TITLE
Landingpage register-button placement

### ISSUE THREAD

**Issue by comlit** [lavaloop-official/GovLearn-client#9]
https://github.com/lavaloop-official/GovLearn-client/blob/65df1cba32125b7dbb6ac23245379d7af4d901bb/src/pages/Landing.tsx#L121

Der Button ist bei mir ohne scrollen nur so halb sichtbar. würde den eher so hinmachen wie in dem Bild. sonst findet susanne den nicht
![image](https://github.com/lavaloop-official/GovLearn-client/assets/67443177/e1345245-f9c6-4349-abbd-8b5fbc33d65f)

**Comment by comlit** [comment]
man kann den auch sonst easy da stehen lassen und einfach einen zweiten oben hin machen

**Comment by Mrjulss** [comment]
> man kann den auch sonst easy da stehen lassen und einfach einen zweiten oben hin machen

ne finde das nach deinem Vorschlag schon besser
